SELECT
  *
FROM
 
  ALUGUEL.INFORMATION_SCHEMA.TABLES;

GO
/*Veridfica todas as tabelas*/
SELECT
  *
FROM
  ALUGUEL.INFORMATION_SCHEMA.TABLES;
GO

/*Cria as tabelas no bd*/
CREATE TABLE USUARIO (
  ID int CHECK (ID > 0) IDENTITY NOT NULL,
  NOME varchar(60) NOT NULL,
  PRIMARY KEY(ID)
) ;

INSERT INTO USUARIO (NOME)
VALUES('Maicon');

 CREATE TABLE AGENTE(
 ID_USUARIO INT IDENTITY(1,1) NOT NULL,
 NUM_PEDIDO INT NOT NULL,
 EMP_BANCO VARCHAR(60) NOT NULL,
 PRIMARY KEY(ID_USUARIO),/* CHAVE PRIMARIA*/
 foreign key(ID_USUARIO) references USUARIO(ID)/*CHAVE ESTRANGEIRA*/
 );

INSERT INTO AGENTE(NUM_PEDIDO, EMP_BANCO)
VALUES (15, 'INTER');

CREATE TABLE CLIENTE(
 ID_USUARIO INT CHECK (ID_USUARIO > 0) NOT NULL,
 RENDIMENTO FLOAT NOT NULL,
 ENDERENCO VARCHAR(60) NOT NULL,
 CPF INT NOT NULL,
 RG INT NOT NULL,
 PROFISSAO VARCHAR(20) NOT NULL,
 ENTIDADE_EMP VARCHAR(50) NOT NULL,
 PRIMARY KEY(ID_USUARIO),/* CHAVE PRIMARIA*/
 foreign key(ID_USUARIO) references USUARIO(ID)/*CHAVE ESTRANGEIRA*/
 );

 INSERT INTO CLIENTE(ID_USUARIO, RENDIMENTO, ENDERENCO, CPF, RG, PROFISSAO, ENTIDADE_EMP)
 VALUES (1, 2.0, 'RUA RUA RUA', 12345678, 12876198, 'VASP', 'PUC MINAS');

 CREATE TABLE AUTOMOVEL(
 MATRICULA INT NOT NULL,
 PLACA CHAR(7) NOT NULL,
 MARCA CHAR(10) NOT NULL,
 MODELO CHAR(10) NOT NULL,
 ANO INT NOT NULL,
 PRIMARY KEY(MATRICULA)/* CHAVE PRIMARIA*/
 );

 INSERT INTO AUTOMOVEL (MATRICULA, PLACA, MARCA, MODELO, ANO)
 VALUES (1234, 'ABC1D23','BMW','AUTOMATICO', 2021);

 CREATE TABLE PEDIDO(
 ID INT CHECK (ID > 0) IDENTITY NOT NULL,
 NOME CHAR(10) NOT NULL,
 DESCRICAO CHAR(20) NOT NULL,
 ID_USUARIO INT CHECK (ID_USUARIO > 0) NOT NULL,
 MATRICULA_AUTOMOVEL INT NOT NULL,
 PRIMARY KEY(ID),/* CHAVE PRIMARIA*/
 foreign key(ID_USUARIO) references USUARIO(ID),/*CHAVE ESTRANGEIRA*/
 foreign key(MATRICULA_AUTOMOVEL) references AUTOMOVEL(MATRICULA)/*CHAVE ESTRANGEIRA*/
 );

 INSERT INTO PEDIDO (NOME, DESCRICAO, ID_USUARIO, MATRICULA_AUTOMOVEL)
 VALUES ('PEDIDO #1', 'CARRO TOP DMS', 1, 1234);

 CREATE TABLE CREDITO(
 ID INT CHECK (ID > 0) IDENTITY NOT NULL,
 AGENTE_CREDITO CHAR(20) NOT NULL,
 VALOR_CREDITO FLOAT NOT NULL,
 PRIMARY KEY(ID)/* CHAVE PRIMARIA*/
 );

 INSERT INTO CREDITO (AGENTE_CREDITO, VALOR_CREDITO)
 VALUES ('CARA DO BIGODE', 65325.55);

 CREATE TABLE CONTRATO(
 ID INT CHECK (ID > 0) IDENTITY NOT NULL,
 TIPO_CONTRATO CHAR(7) NOT NULL,
 ID_PEDIDO INT CHECK (ID_PEDIDO > 0)  NOT NULL,
 ID_CREDITO INT CHECK (ID_CREDITO > 0),
 PRIMARY KEY(ID),/* CHAVE PRIMARIA*/
 foreign key(ID_PEDIDO) references PEDIDO(ID),/*CHAVE ESTRANGEIRA*/
 foreign key(ID_CREDITO) references CREDITO(ID)/*CHAVE ESTRANGEIRA*/
 );

 INSERT INTO CONTRATO (TIPO_CONTRATO, ID_PEDIDO, ID_CREDITO)
 VALUES ('EMPRESA', 1, 1);