
/* CRIAR O BANCO ->*/ CREATE DATABASE ALUGUEL; 

CREATE TABLE `Usuario` (
  ID int(11) UNSIGNED AUTO_INCREMENT NOT NULL,
  NOME varchar(60) NOT NULL,
  PRIMARY KEY(ID)
) ENGINE=InnoDB;


 CREATE TABLE CLIENTE(
 ID_USUARIO INT UNSIGNED NOT NULL,
 RENDIMENTO DOUBLE(9,2) NOT NULL,
 ENDERENCO VARCHAR(60) NOT NULL,
 CPF INT(11) NOT NULL,
 RG INT(8) NOT NULL,
 PROFISSAO VARCHAR(20) NOT NULL,
 ENTIDADE_EMP VARCHAR(50) NOT NULL,
 PRIMARY KEY(ID_USUARIO),/* CHAVE PRIMARIA*/
 foreign key(ID_USUARIO) references USUARIO(ID)/*CHAVE ESTRANGEIRA*/
 )ENGINE=InnoDB;


 CREATE TABLE AGENTE(
 ID_USUARIO INT UNSIGNED NOT NULL,
 NUM_PEDIDO INT(5) NOT NULL,
 EMP_BANCO VARCHAR(60) NOT NULL,
 PRIMARY KEY(ID_USUARIO),/* CHAVE PRIMARIA*/
 foreign key(ID_USUARIO) references USUARIO(ID)/*CHAVE ESTRANGEIRA*/
 )ENGINE=InnoDB;


CREATE TABLE AUTOMOVEL(
 MATRICULA INT(5) NOT NULL,
 PLACA CHAR(7) NOT NULL,
 MARCA CHAR(10) NOT NULL,
 MODELO CHAR(10) NOT NULL,
 ANO INT(4) NOT NULL,
 PRIMARY KEY(MATRICULA)/* CHAVE PRIMARIA*/
 )ENGINE=InnoDB;

CREATE TABLE PEDIDO(
 ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
 NOME CHAR(10) NOT NULL,
 DESCRICAO CHAR(7) NOT NULL,
 ID_USUARIO INT UNSIGNED NOT NULL,
 MATRICULA_AUTOMOVEL INT(5) NOT NULL,
 PRIMARY KEY(ID),/* CHAVE PRIMARIA*/
 foreign key(ID_USUARIO) references USUARIO(ID),/*CHAVE ESTRANGEIRA*/
 foreign key(MATRICULA_AUTOMOVEL) references AUTOMOVEL(MATRICULA)/*CHAVE ESTRANGEIRA*/
 )ENGINE=InnoDB;

 CREATE TABLE CREDITO(
 ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
 AGENTE_CREDITO CHAR(7) NOT NULL,
 VALOR_CREDITO DOUBLE(9,2) NOT NULL,
 PRIMARY KEY(ID)/* CHAVE PRIMARIA*/
 )ENGINE=InnoDB;

CREATE TABLE CONTRATO(
 ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
 TIPO_CONTRATO CHAR(7) NOT NULL,
 ID_PEDIDO INT UNSIGNED  NOT NULL,
 ID_CREDITO INT UNSIGNED,
 PRIMARY KEY(ID),/* CHAVE PRIMARIA*/
 foreign key(ID_PEDIDO) references PEDIDO(ID),/*CHAVE ESTRANGEIRA*/
 foreign key(ID_CREDITO) references CREDITO(ID)/*CHAVE ESTRANGEIRA*/
 )ENGINE=InnoDB;


